import Foundation
public import NostrCore

/// A NIP-46 `nostrconnect://` invitation generated by the client and shown to the signer
/// (as a QR code or deep link):
///
/// ```text
/// nostrconnect://<client-pubkey>?relay=...&secret=...&perms=...&name=...&url=...&image=...
/// ```
///
/// - The host is the client's public key (hex), which originates the connection.
/// - `relay` is a relay the client listens on; it may appear more than once.
/// - `secret` is a random string the signer must echo back to prove it saw the invitation.
/// - `perms` is a comma-separated list of the permissions the client requests.
/// - `name`, `url` and `image` are optional metadata the signer can display.
///
/// https://github.com/nostr-protocol/nips/blob/master/46.md
public struct NostrConnectURI: Sendable, Hashable {
    /// The client's public key (32-byte hex) — the URI origin.
    public let clientPubkey: String

    /// The relays the client listens on. Always at least one.
    public let relays: [URL]

    /// The connection secret the signer must echo back (required by NIP-46).
    public let secret: String

    /// The permissions requested from the signer.
    public let permissions: [RemoteSignerPermission]

    /// The optional client display name shown by the signer.
    public let name: String?

    /// The optional client website shown by the signer.
    public let url: URL?

    /// The optional client icon shown by the signer.
    public let image: URL?

    /// The URI scheme, without the `://` separator.
    public static let scheme = "nostrconnect"

    /// Creates an invitation from its components, validating the client pubkey and relay list.
    ///
    /// - Parameters:
    ///   - clientPubkey: The client's public key (must be 32-byte hex).
    ///   - relays: The relays the client listens on (must contain at least one).
    ///   - secret: The connection secret the signer must echo back.
    ///   - permissions: The permissions requested from the signer.
    ///   - name: An optional client display name.
    ///   - url: An optional client website.
    ///   - image: An optional client icon.
    /// - Throws: ``RemoteSignerError/invalidURI(reason:)`` if any field fails validation.
    public init(
        clientPubkey: String,
        relays: [URL],
        secret: String,
        permissions: [RemoteSignerPermission] = [],
        name: String? = nil,
        url: URL? = nil,
        image: URL? = nil
    ) throws {
        let normalizedPubkey = clientPubkey.lowercased()
        guard Data(hexString: normalizedPubkey)?.count == 32 else {
            throw RemoteSignerError.invalidURI(reason: "client pubkey must be 32-byte hex")
        }
        guard !relays.isEmpty else {
            throw RemoteSignerError.invalidURI(reason: "at least one relay is required")
        }
        guard relays.allSatisfy(URIQuery.isWebSocketURL) else {
            throw RemoteSignerError.invalidURI(reason: "relays must be ws:// or wss:// URLs")
        }

        self.clientPubkey = normalizedPubkey
        self.relays = relays
        self.secret = secret
        self.permissions = permissions
        self.name = name
        self.url = url
        self.image = image
    }

    /// Creates an invitation for `clientKeyPair` with a fresh random 16-byte-hex secret.
    ///
    /// - Parameters:
    ///   - clientKeyPair: The client identity; its public key becomes the URI origin.
    ///   - relays: The relays the client listens on (must contain at least one).
    ///   - permissions: The permissions requested from the signer.
    ///   - name: An optional client display name.
    ///   - url: An optional client website.
    ///   - image: An optional client icon.
    /// - Returns: An invitation carrying a newly minted secret.
    /// - Throws: ``RemoteSignerError/invalidURI(reason:)`` if the relay list is empty.
    public static func invitation(
        clientKeyPair: KeyPair,
        relays: [URL],
        permissions: [RemoteSignerPermission] = [],
        name: String? = nil,
        url: URL? = nil,
        image: URL? = nil
    ) throws -> NostrConnectURI {
        try NostrConnectURI(
            clientPubkey: clientKeyPair.publicKeyHex,
            relays: relays,
            secret: URIQuery.randomHex(byteCount: 16),
            permissions: permissions,
            name: name,
            url: url,
            image: image
        )
    }

    /// Parses a `nostrconnect://` string (round-trip / signer-side).
    ///
    /// - Parameter string: The invitation string produced by a client.
    /// - Throws: ``RemoteSignerError/invalidURI(reason:)`` if the string is malformed or missing
    ///   required fields.
    public init(string: String) throws {
        guard let components = URLComponents(string: string),
            components.scheme?.lowercased() == Self.scheme
        else {
            throw RemoteSignerError.invalidURI(reason: "scheme must be \(Self.scheme)://")
        }

        guard let host = components.host, !host.isEmpty else {
            throw RemoteSignerError.invalidURI(reason: "missing client pubkey")
        }

        let queryItems = components.queryItems ?? []

        let relayValues = queryItems.filter { $0.name == "relay" }.compactMap { $0.value }
        let relays = relayValues.compactMap { URL(string: $0) }
        guard !relayValues.isEmpty, relays.count == relayValues.count else {
            throw RemoteSignerError.invalidURI(reason: "missing or malformed relay")
        }

        guard let secret = queryItems.first(where: { $0.name == "secret" })?.value, !secret.isEmpty else {
            throw RemoteSignerError.invalidURI(reason: "missing secret")
        }

        let permissions =
            (queryItems.first(where: { $0.name == "perms" })?.value)
            .map { value in
                value.split(separator: ",")
                    .map { RemoteSignerPermission(rawValue: String($0)) }
            } ?? []

        let name = queryItems.first(where: { $0.name == "name" })?.value
        let url = (queryItems.first(where: { $0.name == "url" })?.value).flatMap { URL(string: $0) }
        let image = (queryItems.first(where: { $0.name == "image" })?.value).flatMap { URL(string: $0) }

        try self.init(
            clientPubkey: host,
            relays: relays,
            secret: secret,
            permissions: permissions,
            name: name,
            url: url,
            image: image
        )
    }

    /// The invitation string to display as a QR code or deep link, with all values percent-encoded.
    public var stringValue: String {
        var items = relays.map { URLQueryItem(name: "relay", value: $0.absoluteString) }
        items.append(URLQueryItem(name: "secret", value: secret))
        if !permissions.isEmpty {
            items.append(URLQueryItem(name: "perms", value: permissions.map(\.rawValue).joined(separator: ",")))
        }
        if let name {
            items.append(URLQueryItem(name: "name", value: name))
        }
        if let url {
            items.append(URLQueryItem(name: "url", value: url.absoluteString))
        }
        if let image {
            items.append(URLQueryItem(name: "image", value: image.absoluteString))
        }
        return "\(Self.scheme)://\(clientPubkey)?\(URIQuery.encode(items))"
    }
}
